-- MySQL Script generated by MySQL Workbench
-- Fri Feb 22 14:36:04 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `viewgroup3` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `viewgroup3` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`facultad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viewgroup3`.`facultad` (
  `id_facultad` INT NOT NULL,
  `nom_facultad` VARCHAR(45) NULL,
  PRIMARY KEY (`id_facultad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`programa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viewgroup3`.`programa` (
  `id_Programa` INT NOT NULL,
  `nom_progama` VARCHAR(45) NULL,
  `facultad_id_facultad` INT NOT NULL,
  PRIMARY KEY (`id_Programa`),
  INDEX `fk_Programa_facultad1_idx` (`facultad_id_facultad` ASC),
  CONSTRAINT `fk_Programa_facultad1`
    FOREIGN KEY (`facultad_id_facultad`)
    REFERENCES `mydb`.`facultad` (`id_facultad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`grupo_invest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viewgroup3`.`grupo_invest` (
  `id_grupo_invest` INT NOT NULL,
  `nom_grupo` VARCHAR(255) NULL,
  `grupo_investcol` VARCHAR(45) NULL,
  `email_grupo` VARCHAR(45) NULL,
  `telefo_grupo` VARCHAR(45) NULL,
  `direcc_grupo` VARCHAR(45) NULL,
  `url_logo_grupo` VARCHAR(255) NULL,
  `estado_grupo` TINYINT NULL,
  `Programa_id_Programa` INT NOT NULL,
  `siglas_signif_grupo` VARCHAR(450) NULL,
  `objetivo_grupo` VARCHAR(450) NULL,
  `mision_grupo` VARCHAR(450) NULL,
  `vision_grupo` VARCHAR(450) NULL,
  `justif_grupo` VARCHAR(450) NULL,
  `quien_somos_grupo` VARCHAR(45) NULL,
  PRIMARY KEY (`id_grupo_invest`),
  INDEX `fk_grupo_invest_Programa1_idx` (`Programa_id_Programa` ASC),
  CONSTRAINT `fk_grupo_invest_Programa1`
    FOREIGN KEY (`Programa_id_Programa`)
    REFERENCES `mydb`.`programa` (`id_Programa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`semillero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viewgroup3`.`semillero` (
  `id_semillero` INT NOT NULL,
  `nom_semillero` VARCHAR(45) NULL,
  `url_image` VARCHAR(45) NULL,
  `grupo_invest_id_grupo_invest` INT NOT NULL,
  `descrion_semillero` VARCHAR(500) NULL,
  PRIMARY KEY (`id_semillero`, `grupo_invest_id_grupo_invest`),
  INDEX `fk_semillero_grupo_invest1_idx` (`grupo_invest_id_grupo_invest` ASC),
  CONSTRAINT `fk_semillero_grupo_invest1`
    FOREIGN KEY (`grupo_invest_id_grupo_invest`)
    REFERENCES `mydb`.`grupo_invest` (`id_grupo_invest`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`proyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viewgroup3`.`proyecto` (
  `id_produc` INT NOT NULL,
  `nom_proyecto` VARCHAR(45) NULL,
  `fecha_de_produc` DATE NULL,
  `estado_produc` TINYINT NULL,
  `publico_produc` TINYINT NULL,
  `fk_id_grupo_invest` INT NOT NULL,
  `semillero_id_semillero` INT NOT NULL,
  `semillero_grupo_invest_id_grupo_invest` INT NOT NULL,
  PRIMARY KEY (`id_produc`),
  INDEX `fk_producto_grupo_invest1_idx` (`fk_id_grupo_invest` ASC),
  INDEX `fk_proyecto_semillero1_idx` (`semillero_id_semillero` ASC, `semillero_grupo_invest_id_grupo_invest` ASC),
  CONSTRAINT `fk_producto_grupo_invest1`
    FOREIGN KEY (`fk_id_grupo_invest`)
    REFERENCES `mydb`.`grupo_invest` (`id_grupo_invest`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proyecto_semillero1`
    FOREIGN KEY (`semillero_id_semillero` , `semillero_grupo_invest_id_grupo_invest`)
    REFERENCES `mydb`.`semillero` (`id_semillero` , `grupo_invest_id_grupo_invest`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`plantilla`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viewgroup3`.`plantilla` (
  `id_plantilla` INT NOT NULL,
  `nom_plantilla` VARCHAR(255) NULL,
  `url_imagen` VARCHAR(255) NULL,
  PRIMARY KEY (`id_plantilla`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pagina_web`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viewgroup3`.`pagina_web` (
  `id_pagina` INT NOT NULL,
  `url_pagina` VARCHAR(255) NULL,
  `fk_id_plantilla` INT NOT NULL,
  `grupo_invest_id_grupo_invest` INT NOT NULL,
  PRIMARY KEY (`id_pagina`),
  INDEX `fk_pagina_web_plantilla1_idx` (`fk_id_plantilla` ASC),
  INDEX `fk_pagina_web_grupo_invest1_idx` (`grupo_invest_id_grupo_invest` ASC),
  CONSTRAINT `fk_pagina_web_plantilla1`
    FOREIGN KEY (`fk_id_plantilla`)
    REFERENCES `mydb`.`plantilla` (`id_plantilla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pagina_web_grupo_invest1`
    FOREIGN KEY (`grupo_invest_id_grupo_invest`)
    REFERENCES `mydb`.`grupo_invest` (`id_grupo_invest`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viewgroup3`.`usuario` (
  `id_usuario` INT NOT NULL,
  `nom_usuario` VARCHAR(255) NULL,
  `url_foto_usuario` VARCHAR(255) NULL,
  `email_usaurio` VARCHAR(45) NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`grupo_invest_has_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viewgroup3`.`grupo_invest_has_usuario` (
  `grupo_invest_id_grupo_invest` INT NOT NULL,
  `usuario_id_usuario` INT NOT NULL,
  `fecha` VARCHAR(45) NULL,
  PRIMARY KEY (`grupo_invest_id_grupo_invest`, `usuario_id_usuario`),
  INDEX `fk_grupo_invest_has_usuario_usuario1_idx` (`usuario_id_usuario` ASC),
  INDEX `fk_grupo_invest_has_usuario_grupo_invest1_idx` (`grupo_invest_id_grupo_invest` ASC),
  CONSTRAINT `fk_grupo_invest_has_usuario_grupo_invest1`
    FOREIGN KEY (`grupo_invest_id_grupo_invest`)
    REFERENCES `mydb`.`grupo_invest` (`id_grupo_invest`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_grupo_invest_has_usuario_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viewgroup3`.`tipo_usuario` (
  `id_rol` INT NOT NULL,
  `nom_rol` VARCHAR(45) NULL,
  `grupo_invest_has_usuario_grupo_invest_id_grupo_invest` INT NOT NULL,
  `grupo_invest_has_usuario_usuario_id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_rol`),
  INDEX `fk_tipo_usuario_grupo_invest_has_usuario1_idx` (`grupo_invest_has_usuario_grupo_invest_id_grupo_invest` ASC, `grupo_invest_has_usuario_usuario_id_usuario` ASC),
  CONSTRAINT `fk_tipo_usuario_grupo_invest_has_usuario1`
    FOREIGN KEY (`grupo_invest_has_usuario_grupo_invest_id_grupo_invest` , `grupo_invest_has_usuario_usuario_id_usuario`)
    REFERENCES `mydb`.`grupo_invest_has_usuario` (`grupo_invest_id_grupo_invest` , `usuario_id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`actividad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viewgroup3`.`actividad` (
  `id_Actividad` INT NOT NULL,
  `nom_actividad` VARCHAR(255) NULL,
  `descripcion_actividad` VARCHAR(255) NULL,
  `fecha_actividad` DATE NULL,
  `grupo_invest_id_grupo_invest` INT NOT NULL,
  PRIMARY KEY (`id_Actividad`, `grupo_invest_id_grupo_invest`),
  INDEX `fk_Actividad_grupo_invest1_idx` (`grupo_invest_id_grupo_invest` ASC),
  CONSTRAINT `fk_Actividad_grupo_invest1`
    FOREIGN KEY (`grupo_invest_id_grupo_invest`)
    REFERENCES `mydb`.`grupo_invest` (`id_grupo_invest`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viewgroup3`.`categoria` (
  `id_Categoria` INT NOT NULL,
  `id_nom_categoria` VARCHAR(45) NULL,
  `estado_categoria` VARCHAR(45) NULL,
  PRIMARY KEY (`id_Categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`soporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viewgroup3`.`soporte` (
  `id_soporte` INT NOT NULL,
  `url_imagene` VARCHAR(255) NULL,
  `titulo_soporte` VARCHAR(255) NULL,
  `descrip_soperte` VARCHAR(255) NULL,
  `estado_soporte` VARCHAR(45) NULL,
  `Fecha_publica` DATE NULL,
  `Categoria_id_Categoria` INT NOT NULL,
  `grupo_invest_id_grupo_invest` INT NOT NULL,
  PRIMARY KEY (`id_soporte`),
  INDEX `fk_soporte_Categoria1_idx` (`Categoria_id_Categoria` ASC),
  INDEX `fk_soporte_grupo_invest1_idx` (`grupo_invest_id_grupo_invest` ASC),
  CONSTRAINT `fk_soporte_Categoria1`
    FOREIGN KEY (`Categoria_id_Categoria`)
    REFERENCES `mydb`.`categoria` (`id_Categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_soporte_grupo_invest1`
    FOREIGN KEY (`grupo_invest_id_grupo_invest`)
    REFERENCES `mydb`.`grupo_invest` (`id_grupo_invest`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`auditoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viewgroup3`.`auditoria` (
  `id_auditoria` INT NOT NULL,
  `nom_grupo` VARCHAR(45) NULL,
  `nom_usuario` VARCHAR(45) NULL,
  `fecha_acciion` VARCHAR(45) NULL,
  PRIMARY KEY (`id_auditoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viewgroup3`.`menu` (
  `id_menu` INT NOT NULL,
  `nom_menu` VARCHAR(45) NULL,
  `id_menu_padre` VARCHAR(45) NULL,
  `url_pagina` VARCHAR(45) NULL,
  `icono` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  PRIMARY KEY (`id_menu`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_usuario_has_Menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viewgroup3`.`tipo_usuario_has_Menu` (
  `tipo_usuario_id_rol` INT NOT NULL,
  `Menu_id_menu` INT NOT NULL,
  `fecha_menu` VARCHAR(45) NULL,
  PRIMARY KEY (`tipo_usuario_id_rol`, `Menu_id_menu`),
  INDEX `fk_tipo_usuario_has_Menu_Menu1_idx` (`Menu_id_menu` ASC),
  INDEX `fk_tipo_usuario_has_Menu_tipo_usuario1_idx` (`tipo_usuario_id_rol` ASC),
  CONSTRAINT `fk_tipo_usuario_has_Menu_tipo_usuario1`
    FOREIGN KEY (`tipo_usuario_id_rol`)
    REFERENCES `mydb`.`tipo_usuario` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tipo_usuario_has_Menu_Menu1`
    FOREIGN KEY (`Menu_id_menu`)
    REFERENCES `mydb`.`menu` (`id_menu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`habilidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viewgroup3`.`habilidades` (
  `id_Habilidades` INT NOT NULL,
  `nom_Habili` VARCHAR(45) NULL,
  `estado_habili` VARCHAR(45) NULL,
  PRIMARY KEY (`id_Habilidades`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pagina Propia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viewgroup3`.`Pagina Propia` (
  `id_Pagina Propia` INT NOT NULL,
  `Nom_grupo` VARCHAR(45) NULL,
  `Contenido` VARCHAR(45) NULL,
  `Creadores` VARCHAR(45) NULL,
  `Acredicimiento` VARCHAR(45) NULL,
  `Logo` VARCHAR(45) NULL,
  PRIMARY KEY (`id_Pagina Propia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`habilidades_has_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viewgroup3`.`habilidades_has_usuario` (
  `habilidades_id_Habilidades` INT NOT NULL,
  `usuario_id_usuario` INT NOT NULL,
  `fecha_habilidad` VARCHAR(45) NULL,
  PRIMARY KEY (`habilidades_id_Habilidades`, `usuario_id_usuario`),
  INDEX `fk_habilidades_has_usuario_usuario1_idx` (`usuario_id_usuario` ASC),
  INDEX `fk_habilidades_has_usuario_habilidades1_idx` (`habilidades_id_Habilidades` ASC),
  CONSTRAINT `fk_habilidades_has_usuario_habilidades1`
    FOREIGN KEY (`habilidades_id_Habilidades`)
    REFERENCES `mydb`.`habilidades` (`id_Habilidades`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_habilidades_has_usuario_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
